### ISSUE TITLE
Cannot start server within MineOS webUI

### ISSUE THREAD

**Issue by ckbisek** [tucks/mineos-bedrock-wrapper#1]
I have confirmed that I am able to start the Bedrock server via CLI, however, after following instructions in README I am unable to start Bedrock server within MineOS webUI.  We have a Java server running just fine and controlled by the MineOS webUI

**Comment by ckbisek** [comment]
If I start a screen session specifically named, then it appears the MineOS WebUI does reflect that the server is running...or I'm just an idiot

`screen -S mc-bedrock1`
`mcserver@ubuntuserver:/var/games/minecraft/servers/bedrock1$ LD_LIBRARY_PATH=. ./bedrock_server`

**Comment by ckbisek** [comment]
```
mcserver@ubuntuserver:/var/games/minecraft/servers/bedrock1$ java -jar mineos-bedrock-wrapper-1.0-SNAPSHOT.jar
Error: Invalid or corrupt jarfile mineos-bedrock-wrapper-1.0-SNAPSHOT.jar
mcserver@ubuntuserver:/var/games/minecraft/servers/bedrock1$ rm mineos-bedrock-wrapper-1.0-SNAPSHOT.jar
```
I downloaded the jar manually (outside of the MineOS UI) and was able to successfully start the server within the MineOS UI

**Comment by tucks** [comment]
Hello there.  Apologies for the late response.  Work intervened.
I have added an md5 checksum to the folder where the jar so you can validate its integrity.

Super that you have managed to start bedrock in the MineOS UI.
How has the jar performed?  Any issues?

Note that this implementation as suggested in the readme docs of this repo is being replaced by a newer method.
There is a PR open in the mineos project for an in-product integration.

**Comment by ckbisek** [comment]
@tucks 
No need to apologize; life takes precedence
It has worked out great, no further issues

**Comment by tucks** [comment]
Superb.  I'll close this off.
Please ping me with any further insight/requirements as necessary.
