### ISSUE TITLE
MineOS-node patch js is downloading html file and not actual jar file.

### ISSUE THREAD

**Issue by WinFinn** [tucks/mineos-bedrock-wrapper#2]
Following step 1 here:  https://github.com/tucks/mineos-bedrock-wrapper/tree/master/mineos-node_patch
Using the minecraftbedrockwrapper.js to download profile within MineOS webui will result in that the jar file downloaded actually is a html file and not a jar file. (see [hexparrots comments on your request](https://github.com/hexparrot/mineos-node/pull/432)).

**Comment by tucks** [comment]
Hello there.
Thank you for the bump.  I had indeed forgotten to change that reference and have now updated it to the raw blob.
The ultimate intention is to merge in the bedrock into core mineos-node, after which this repo should not be required.
Could you see if the latest push to master has resolved the issue for you?

**Comment by WinFinn** [comment]
I did download the new one as I described on MineOS forum and it worked fine this time.
For the mineos-node integration I suspect you'll need better documentation for the installation, before it'll be integrated. There is just to many manual steps after profile installation that is not detailed enough.

**Comment by tucks** [comment]
This is resolved and merged into mineos-node v1.2.1.
I'll close this off.
